name: SpawnerSystem
version: ${project.version}
main: me.spawner.Spawner
api-version: '1.20'
author: onur1692
description: Advanced and configurable spawner plugin.
folia-supported: true
softdepend: [ProtocolLib]

commands:
  spsystem:
    description: Main command for the Spawner System.
    aliases: [sps]
    permission: spawner.admin